version: '3.7'

services:
  events_api:
    environment:
      - MONGO_URL=mongodb://db:27017
      - REDIS_URL=redis://redis:6379
    build:
      context: .
      dockerfile: ./events_api/Dockerfile
    ports:
      - "8000:8000"
    hostname: events_api
    container_name: events_api
  files_api:
    environment:
      - MONGO_URL=mongodb://db:27017
      - REDIS_URL=redis://redis:6379
    build:
      context: .
      dockerfile: ./files_api/Dockerfile
    ports:
      - "8001:8001"
    hostname: files_api
    container_name: files_api
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: db
    hostname: db
    volumes: 
      - ./mongo_data:/data/db
  redis:
    image: 'bitnami/redis:latest'
    ports:
      - "6379:6379"
    hostname: redis
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    container_name: prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    container_name: grafana
    volumes:
      - ./grafana_data:/var/lib/grafana